// =========================================================
// ポケモンデータ  ← ここだけ編集・AI投げ対象
//
// 各フィールド:
//   rank         : 使用率順位 (シーズンM-A シングル)
//   name         : ポケモン名
//   types        : タイプ (1〜2個)
//   immune_types : 特性によって無効化できる攻撃タイプの配列
//   resist_types : 特性によって半減できる攻撃タイプの配列
//
// =========================================================

// =========================================================
// 未実装特性メモ（計算への影響が複雑なため保留）
//
// こおりのりんぷん : 特殊技で受けるダメージを半減
// ハードロック     : 効果抜群の技で受けるダメージを3/4
// ファーコート     : 効果抜群の技で受けるダメージを3/4
// ファントムガード : HP満タン時、受けるダメージを半減
// フィルター       : 効果抜群の技で受けるダメージを3/4
// フレンドガード   : ダブルで味方が受けるダメージを3/4（シングル無関係）
// もふもふ         : 直接攻撃を半減・ほのお技は2倍
// プリズムアーマー : 効果抜群の技で受けるダメージを3/4
// アイスフェイス   : 物理技のダメージを1度だけ無効
// ばけのかわ       : 技のダメージを1度だけ無効
// いかく           : 相手の攻撃を1段階下げる（ダメージ軽減ではない）
// わざわいのうつわ : 自分以外の特攻を3/4（攻撃側の特性）
// わざわいのおふだ : 自分以外の攻撃を3/4（攻撃側の特性）
// =========================================================


const POKEMON_LIST = [
  { rank: 1, name: "ガブリアス", slug: "garchomp", types: ["ドラゴン", "じめん"], immune_types: [], resist_types: [] },
  { rank: 1.1, name: "メガガブリアス", slug: "garchomp-mega", types: ["ドラゴン", "じめん"], immune_types: [], resist_types: [] },
  { rank: 2, name: "ミミッキュ", slug: "mimikyu", types: ["ゴースト", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 3, name: "マスカーニャ", slug: "meowscarada", types: ["くさ", "あく"], immune_types: [], resist_types: [] },
  { rank: 4, name: "メタグロス", slug: "metagross", types: ["はがね", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 4.1, name: "メガメタグロス", slug: "metagross-mega", types: ["はがね", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 5, name: "ブリジュラス", slug: "archaludon", types: ["はがね", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 6, name: "リザードン", slug: "charizard", types: ["ほのお", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 6.1, name: "メガリザードンX", slug: "charizard-mega-x", types: ["ほのお", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 6.2, name: "メガリザードンY", slug: "charizard-mega-y", types: ["ほのお", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 7, name: "カバルドン", slug: "hippowdon", types: ["じめん"], immune_types: [], resist_types: [] },
  { rank: 8, name: "ライチュウ", slug: "raichu", types: ["でんき"], immune_types: ["でんき"], resist_types: [] },
  { rank: 8.1, name: "メガライチュウX", slug: "raichu-mega-x", types: ["でんき"], immune_types: [], resist_types: [] },
  { rank: 8.2, name: "メガライチュウY", slug: "raichu-mega-y", types: ["でんき"], immune_types: [], resist_types: [] },
  { rank: 9, name: "キュウコン(アローラ)", slug: "ninetales-alola", types: ["こおり", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 10, name: "バシャーモ", slug: "blaziken", types: ["ほのお", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 10.1, name: "メガバシャーモ", slug: "blaziken-mega", types: ["ほのお", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 11, name: "アーマーガア", slug: "corviknight", types: ["ひこう", "はがね"], immune_types: [], resist_types: [] },
  { rank: 12, name: "サザンドラ", slug: "hydreigon", types: ["あく", "ドラゴン"], immune_types: ["じめん"], resist_types: [] },
  { rank: 13, name: "ムクホーク", slug: "staraptor", types: ["ノーマル", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 13.1, name: "メガムクホーク", slug: "staraptor-mega", types: ["かくとう", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 14, name: "アシレーヌ", slug: "primarina", types: ["みず", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 15, name: "ギャラドス", slug: "gyarados", types: ["みず", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 15.1, name: "メガギャラドス", slug: "gyarados-mega", types: ["みず", "あく"], immune_types: [], resist_types: [] },
  { rank: 16, name: "マフォクシー", slug: "delphox", types: ["ほのお", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 16.1, name: "メガマフォクシー", slug: "delphox-mega", types: ["ほのお", "エスパー"], immune_types: ["じめん"], resist_types: [] },
  { rank: 17, name: "イダイトウ(オス)", slug: "basculegion", types: ["みず", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 18, name: "キラフロル", slug: "glimmora", types: ["いわ", "どく"], immune_types: [], resist_types: [] },
  { rank: 18.1, name: "メガキラフロル", slug: "glimmora-mega", types: ["いわ", "どく"], immune_types: [], resist_types: [] },
  { rank: 19, name: "ラグラージ", slug: "swampert", types: ["みず", "じめん"], immune_types: [], resist_types: [] },
  { rank: 19.1, name: "メガラグラージ", slug: "swampert-mega", types: ["みず", "じめん"], immune_types: [], resist_types: [] },
  { rank: 20, name: "ウォッシュロトム", slug: "rotom-wash", types: ["でんき", "みず"], immune_types: ["じめん"], resist_types: [] },
  { rank: 21, name: "カイリュー", slug: "dragonite", types: ["ドラゴン", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 21.1, name: "メガカイリュー", slug: "dragonite-mega", types: ["ドラゴン", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 22, name: "ゲッコウガ", slug: "greninja", types: ["みず", "あく"], immune_types: [], resist_types: [] },
  { rank: 22.1, name: "メガゲッコウガ", slug: "greninja-mega", types: ["みず", "あく"], immune_types: [], resist_types: [] },
  { rank: 23, name: "オーロンゲ", slug: "grimmsnarl", types: ["あく", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 24, name: "クチート", slug: "mawile", types: ["はがね", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 24.1, name: "メガクチート", slug: "mawile-mega", types: ["はがね", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 25, name: "ラウドボーン", slug: "skeledirge", types: ["ほのお", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 26, name: "サーフゴー", slug: "gholdengo", types: ["はがね", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 27, name: "ペリッパー", slug: "pelipper", types: ["みず", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 28, name: "ドドゲザン", slug: "kingambit", types: ["あく", "はがね"], immune_types: [], resist_types: [] },
  { rank: 29, name: "ゲンガー", slug: "gengar", types: ["ゴースト", "どく"], immune_types: [], resist_types: [] },
  { rank: 29.1, name: "メガゲンガー", slug: "gengar-mega", types: ["ゴースト", "どく"], immune_types: [], resist_types: [] },
  { rank: 30, name: "ギルガルド", slug: "aegislash", types: ["はがね", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 31, name: "ドラミドロ", slug: "dragalge", types: ["どく", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 31.1, name: "メガドラミドロ", slug: "dragalge-mega", types: ["どく", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 32, name: "ドラパルト", slug: "dragapult", types: ["ドラゴン", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 33, name: "ハッサム", slug: "scizor", types: ["むし", "はがね"], immune_types: [], resist_types: [] },
  { rank: 33.1, name: "メガハッサム", slug: "scizor-mega", types: ["むし", "はがね"], immune_types: [], resist_types: [] },
  { rank: 34, name: "ダイケンキ(ヒスイ)", slug: "samurott-hisui", types: ["みず", "あく"], immune_types: [], resist_types: [] },
  { rank: 35, name: "ウルガモス", slug: "volcarona", types: ["むし", "ほのお"], immune_types: [], resist_types: [] },
  { rank: 36, name: "ソウブレイズ", slug: "ceruledge", types: ["ほのお", "ゴースト"], immune_types: ["ほのお"], resist_types: [] },
  { rank: 37, name: "スターミー", slug: "starmie", types: ["みず", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 37.1, name: "メガスターミー", slug: "starmie-mega", types: ["みず", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 38, name: "ミミロップ", slug: "lopunny", types: ["ノーマル"], immune_types: [], resist_types: [] },
  { rank: 38.1, name: "メガミミロップ", slug: "lopunny-mega", types: ["ノーマル", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 39, name: "ブラッキー", slug: "umbreon", types: ["あく"], immune_types: [], resist_types: [] },
  { rank: 40, name: "バイバニラ", slug: "vanilluxe", types: ["こおり"], immune_types: [], resist_types: [] },
  { rank: 41, name: "メガニウム", slug: "meganium", types: ["くさ"], immune_types: [], resist_types: [] },
  { rank: 41.1, name: "メガメガニウム", slug: "meganium-mega", types: ["くさ", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 42, name: "フシギバナ", slug: "venusaur", types: ["くさ", "どく"], immune_types: [], resist_types: [] },
  { rank: 42.1, name: "メガフシギバナ", slug: "venusaur-mega", types: ["くさ", "どく"], immune_types: [], resist_types: ["ほのお", "こおり"] },
  { rank: 43, name: "オオニューラ", slug: "sneasler", types: ["かくとう", "どく"], immune_types: [], resist_types: [] },
  { rank: 44, name: "ルカリオ", slug: "lucario", types: ["かくとう", "はがね"], immune_types: [], resist_types: [] },
  { rank: 44.1, name: "メガルカリオ", slug: "lucario-mega", types: ["かくとう", "はがね"], immune_types: [], resist_types: [] },
  { rank: 45, name: "カメックス", slug: "blastoise", types: ["みず"], immune_types: [], resist_types: [] },
  { rank: 45.1, name: "メガカメックス", slug: "blastoise-mega", types: ["みず"], immune_types: [], resist_types: [] },
  { rank: 46, name: "コノヨザル", slug: "annihilape", types: ["かくとう", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 47, name: "ニンフィア", slug: "sylveon", types: ["フェアリー"], immune_types: [], resist_types: [] },
  { rank: 48, name: "ハラバリー", slug: "bellibolt", types: ["でんき"], immune_types: [], resist_types: [] },
  { rank: 49, name: "ドヒドイデ", slug: "toxapex", types: ["どく", "みず"], immune_types: [], resist_types: [] },
  { rank: 50, name: "バンギラス", slug: "tyranitar", types: ["いわ", "あく"], immune_types: [], resist_types: [] },
  { rank: 50.1, name: "メガバンギラス", slug: "tyranitar-mega", types: ["いわ", "あく"], immune_types: [], resist_types: [] },
  { rank: 51, name: "マンムー", slug: "mamoswine", types: ["こおり", "じめん"], immune_types: [], resist_types: ["ほのお", "こおり"] },
  { rank: 52, name: "エルフーン", slug: "whimsicott", types: ["くさ", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 53, name: "ドリュウズ", slug: "excadrill", types: ["じめん", "はがね"], immune_types: [], resist_types: [] },
  { rank: 53.1, name: "メガドリュウズ", slug: "excadrill-mega", types: ["じめん", "はがね"], immune_types: [], resist_types: [] },
  { rank: 54, name: "ピクシー", slug: "clefable", types: ["フェアリー"], immune_types: [], resist_types: [] },
  { rank: 54.1, name: "メガピクシー", slug: "clefable-mega", types: ["フェアリー", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 55, name: "ヒートロトム", slug: "rotom-heat", types: ["でんき", "ほのお"], immune_types: ["じめん"], resist_types: [] },
  { rank: 56, name: "マリルリ", slug: "azumarill", types: ["みず", "フェアリー"], immune_types: ["くさ"], resist_types: ["ほのお", "こおり"] },
  { rank: 57, name: "ゾロアーク(ヒスイ)", slug: "zoroark-hisui", types: ["ノーマル", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 58, name: "ミロカロス", slug: "milotic", types: ["みず"], immune_types: [], resist_types: [] },
  { rank: 59, name: "クエスパトラ", slug: "espathra", types: ["エスパー"], immune_types: [], resist_types: [] },
  { rank: 60, name: "フラエッテ(永遠)", slug: "floette-eternal", types: ["フェアリー"], immune_types: [], resist_types: [] },
  { rank: 60.1, name: "メガフラエッテ", slug: "floette-mega", types: ["フェアリー"], immune_types: [], resist_types: [] },
  { rank: 61, name: "ユキメノコ", slug: "froslass", types: ["こおり", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 61.1, name: "メガユキメノコ", slug: "froslass-mega", types: ["こおり", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 62, name: "カビゴン", slug: "snorlax", types: ["ノーマル"], immune_types: [], resist_types: ["ほのお", "こおり"] },
  { rank: 63, name: "メタモン", slug: "ditto", types: ["ノーマル"], immune_types: [], resist_types: [] },
  { rank: 64, name: "オニシズクモ", slug: "araquanid", types: ["みず", "むし"], immune_types: ["みず"], resist_types: ["ほのお"] },
  { rank: 65, name: "エアームド", slug: "skarmory", types: ["はがね", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 65.1, name: "メガエアームド", slug: "skarmory-mega", types: ["はがね", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 66, name: "サーナイト", slug: "gardevoir", types: ["エスパー", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 66.1, name: "メガサーナイト", slug: "gardevoir-mega", types: ["エスパー", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 67, name: "ヤバソチャ", slug: "sinistcha", types: ["くさ", "ゴースト"], immune_types: [], resist_types: ["ほのお"] },
  { rank: 68, name: "ジュカイン", slug: "sceptile", types: ["くさ"], immune_types: [], resist_types: [] },
  { rank: 68.1, name: "メガジュカイン", slug: "sceptile-mega", types: ["くさ", "ドラゴン"], immune_types: ["でんき"], resist_types: [] },
  { rank: 69, name: "ジャローダ", slug: "serperior", types: ["くさ"], immune_types: [], resist_types: [] },
  { rank: 70, name: "ガルーラ", slug: "kangaskhan", types: ["ノーマル"], immune_types: [], resist_types: [] },
  { rank: 70.1, name: "メガガルーラ", slug: "kangaskhan-mega", types: ["ノーマル"], immune_types: [], resist_types: [] },
  { rank: 71, name: "スコヴィラン", slug: "scovillain", types: ["くさ", "ほのお"], immune_types: [], resist_types: [] },
  { rank: 71.1, name: "メガスコヴィラン", slug: "scovillain-mega", types: ["くさ", "ほのお"], immune_types: [], resist_types: [] },
  { rank: 72, name: "ヤミラミ", slug: "sableye", types: ["あく", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 72.1, name: "メガヤミラミ", slug: "sableye-mega", types: ["あく", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 73, name: "ガオガエン", slug: "incineroar", types: ["ほのお", "あく"], immune_types: [], resist_types: [] },
  { rank: 74, name: "バサギリ", slug: "kleavor", types: ["むし", "いわ"], immune_types: [], resist_types: [] },
  { rank: 75, name: "シビルドン", slug: "eelektross", types: ["でんき"], immune_types: ["じめん"], resist_types: [] },
  { rank: 75.1, name: "メガシビルドン", slug: "eelektross-mega", types: ["でんき"], immune_types: ["じめん"], resist_types: [] },
  { rank: 76, name: "イッカネズミ", slug: "maushold", types: ["ノーマル"], immune_types: [], resist_types: [] },
  { rank: 77, name: "エルレイド", slug: "gallade", types: ["エスパー", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 77.1, name: "メガエルレイド", slug: "gallade-mega", types: ["エスパー", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 78, name: "グレンアルマ", slug: "armarouge", types: ["ほのお", "エスパー"], immune_types: ["ほのお"], resist_types: [] },
  { rank: 79, name: "ヤドラン", slug: "slowbro", types: ["みず", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 79.1, name: "メガヤドラン", slug: "slowbro-mega", types: ["みず", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 80, name: "ペンドラー", slug: "scolipede", types: ["むし", "どく"], immune_types: [], resist_types: [] },
  { rank: 80.1, name: "メガペンドラー", slug: "scolipede-mega", types: ["むし", "どく"], immune_types: [], resist_types: [] },
  { rank: 81, name: "ブリムオン", slug: "hatterene", types: ["エスパー", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 82, name: "ジュペッタ", slug: "banette", types: ["ゴースト"], immune_types: [], resist_types: [] },
  { rank: 82.1, name: "メガジュペッタ", slug: "banette-mega", types: ["ゴースト"], immune_types: [], resist_types: [] },
  { rank: 83, name: "ズルズキン", slug: "scrafty", types: ["あく", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 83.1, name: "メガズルズキン", slug: "scrafty-mega", types: ["あく", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 84, name: "ヌメルゴン(ヒスイ)", slug: "goodra-hisui", types: ["はがね", "ドラゴン"], immune_types: ["くさ"], resist_types: [] },
  { rank: 85, name: "ラフレシア", slug: "vileplume", types: ["くさ", "どく"], immune_types: [], resist_types: [] },
  { rank: 86, name: "エンペルト", slug: "empoleon", types: ["みず", "はがね"], immune_types: [], resist_types: [] },
  { rank: 87, name: "シャンデラ", slug: "chandelure", types: ["ゴースト", "ほのお"], immune_types: ["ほのお"], resist_types: [] },
  { rank: 87.1, name: "メガシャンデラ", slug: "chandelure-mega", types: ["ゴースト", "ほのお"], immune_types: [], resist_types: [] },
  { rank: 88, name: "ビビヨン", slug: "vivillon", types: ["むし", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 89, name: "ホルード", slug: "diggersby", types: ["ノーマル", "じめん"], immune_types: [], resist_types: [] },
  { rank: 90, name: "ポットデス", slug: "polteageist", types: ["ゴースト"], immune_types: [], resist_types: [] },
  { rank: 91, name: "ユキノオー", slug: "abomasnow", types: ["くさ", "こおり"], immune_types: [], resist_types: [] },
  { rank: 91.1, name: "メガユキノオー", slug: "abomasnow-mega", types: ["くさ", "こおり"], immune_types: [], resist_types: [] },
  { rank: 92, name: "ヤドキング(ガラル)", slug: "slowking-galar", types: ["どく", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 93, name: "ウインディ(ヒスイ)", slug: "arcanine-hisui", types: ["ほのお", "いわ"], immune_types: ["ほのお"], resist_types: [] },
  { rank: 94, name: "ミミズズ", slug: "orthworm", types: ["はがね"], immune_types: ["じめん"], resist_types: [] },
  { rank: 95, name: "カエンジシ", slug: "pyroar", types: ["ほのお", "ノーマル"], immune_types: [], resist_types: [] },
  { rank: 95.1, name: "メガカエンジシ", slug: "pyroar-mega", types: ["ノーマル", "ほのお"], immune_types: [], resist_types: [] },
  { rank: 96, name: "ドデカバシ", slug: "toucannon", types: ["ノーマル", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 97, name: "グライオン", slug: "gliscor", types: ["じめん", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 98, name: "ガメノデス", slug: "barbaracle", types: ["ほのお", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 98.1, name: "メガガメノデス", slug: "barbaracle-mega", types: ["いわ", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 99, name: "デカヌチャン", slug: "tinkaton", types: ["フェアリー", "はがね"], immune_types: [], resist_types: [] },
  { rank: 100, name: "ローブシン", slug: "conkeldurr", types: ["かくとう"], immune_types: [], resist_types: [] },
  { rank: 101, name: "イルカマン", slug: "palafin", types: ["みず"], immune_types: [], resist_types: [] },
  { rank: 102, name: "ウツボット", slug: "victreebel", types: ["くさ", "どく"], immune_types: [], resist_types: [] },
  { rank: 102.1, name: "メガウツボット", slug: "victreebel-mega", types: ["くさ", "どく"], immune_types: [], resist_types: [] },
  { rank: 103, name: "ブリガロン", slug: "chesnaught", types: ["くさ", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 103.1, name: "メガブリガロン", slug: "chesnaught-mega", types: ["くさ", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 104, name: "シャワーズ", slug: "vaporeon", types: ["みず"], immune_types: ["みず"], resist_types: [] },
  { rank: 105, name: "ハカドッグ", slug: "houndstone", types: ["ゴースト"], immune_types: [], resist_types: [] },
  { rank: 106, name: "ボスゴドラ", slug: "aggron", types: ["はがね", "いわ"], immune_types: [], resist_types: [] },
  { rank: 106.1, name: "メガボスゴドラ", slug: "aggron-mega", types: ["はがね"], immune_types: [], resist_types: [] },
  { rank: 107, name: "イダイトウ(メス)", slug: "basculegion-f", types: ["みず", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 108, name: "プテラ", slug: "aerodactyl", types: ["いわ", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 108.1, name: "メガプテラ", slug: "aerodactyl-mega", types: ["いわ", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 109, name: "ハリーマン", slug: "overqwil", types: ["あく", "どく"], immune_types: [], resist_types: [] },
  { rank: 110, name: "エレザード", slug: "heliolisk", types: ["でんき", "ノーマル"], immune_types: ["みず"], resist_types: [] },
  { rank: 111, name: "ヘラクロス", slug: "heracross", types: ["むし", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 111.1, name: "メガヘラクロス", slug: "heracross-mega", types: ["むし", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 112, name: "サメハダー", slug: "sharpedo", types: ["みず", "あく"], immune_types: [], resist_types: [] },
  { rank: 112.1, name: "メガサメハダー", slug: "sharpedo-mega", types: ["みず", "あく"], immune_types: [], resist_types: [] },
  { rank: 113, name: "エーフィ", slug: "espeon", types: ["エスパー"], immune_types: [], resist_types: [] },
  { rank: 114, name: "マニューラ", slug: "weavile", types: ["あく", "こおり"], immune_types: [], resist_types: [] },
  { rank: 115, name: "デスバーン", slug: "runerigus", types: ["じめん", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 116, name: "ヤドラン(ガラル)", slug: "slowbro-galar", types: ["どく", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 117, name: "ウェーニバル", slug: "quaquaval", types: ["みず", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 118, name: "ウインディ", slug: "arcanine", types: ["ほのお"], immune_types: ["ほのお"], resist_types: [] },
  { rank: 119, name: "フーディン", slug: "alakazam", types: ["エスパー"], immune_types: [], resist_types: [] },
  { rank: 119.1, name: "メガフーディン", slug: "alakazam-mega", types: ["エスパー"], immune_types: [], resist_types: [] },
  { rank: 120, name: "コータス", slug: "torkoal", types: ["ほのお"], immune_types: [], resist_types: [] },
  { rank: 121, name: "ファイアロー", slug: "talonflame", types: ["ほのお", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 122, name: "オーダイル", slug: "feraligatr", types: ["みず"], immune_types: [], resist_types: [] },
  { rank: 122.1, name: "メガオーダイル", slug: "feraligatr-mega", types: ["みず", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 123, name: "バクフーン(ヒスイ)", slug: "typhlosion-hisui", types: ["ほのお", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 124, name: "カットロトム", slug: "rotom-mow", types: ["でんき", "くさ"], immune_types: ["じめん"], resist_types: [] },
  { rank: 125, name: "ニョロトノ", slug: "politoed", types: ["みず"], immune_types: ["みず"], resist_types: [] },
  { rank: 126, name: "ゴウカザル", slug: "infernape", types: ["ほのお", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 127, name: "エンニュート", slug: "salazzle", types: ["どく", "ほのお"], immune_types: [], resist_types: [] },
  { rank: 128, name: "ケンタロス(炎)", slug: "tauros-paldea-blaze", types: ["かくとう", "ほのお"], immune_types: [], resist_types: [] },
  { rank: 129, name: "ジュナイパー(ヒスイ)", slug: "decidueye-hisui", types: ["くさ", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 130, name: "デスカーン", slug: "cofagrigus", types: ["ゴースト"], immune_types: [], resist_types: [] },
  { rank: 131, name: "チルタリス", slug: "altaria", types: ["ドラゴン", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 131.1, name: "メガチルタリス", slug: "altaria-mega", types: ["ドラゴン", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 132, name: "ルガルガン(たそがれ)", slug: "lycanroc-dusk", types: ["いわ"], immune_types: [], resist_types: [] },
  { rank: 133, name: "ランクルス", slug: "reuniclus", types: ["エスパー"], immune_types: [], resist_types: [] },
  { rank: 134, name: "バンバドロ", slug: "mudsdale", types: ["じめん"], immune_types: [], resist_types: [] },
  { rank: 135, name: "ルチャブル", slug: "hawlucha", types: ["かくとう", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 135.1, name: "メガルチャブル", slug: "hawlucha-mega", types: ["かくとう", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 136, name: "グレイシア", slug: "glaceon", types: ["こおり"], immune_types: [], resist_types: [] },
  { rank: 137, name: "スピアー", slug: "beedrill", types: ["むし", "どく"], immune_types: [], resist_types: [] },
  { rank: 137.1, name: "メガスピアー", slug: "beedrill-mega", types: ["むし", "どく"], immune_types: [], resist_types: [] },
  { rank: 138, name: "カイロス", slug: "pinsir", types: ["むし"], immune_types: [], resist_types: [] },
  { rank: 138.1, name: "メガカイロス", slug: "pinsir-mega", types: ["むし", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 139, name: "カラマネロ", slug: "malamar", types: ["あく", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 139.1, name: "メガカラマネロ", slug: "malamar-mega", types: ["あく", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 140, name: "チリーン", slug: "chimecho", types: ["エスパー"], immune_types: ["じめん"], resist_types: [] },
  { rank: 140.1, name: "メガチリーン", slug: "chimecho-mega", types: ["エスパー", "はがね"], immune_types: ["じめん"], resist_types: [] },
  { rank: 141, name: "クレッフィ", slug: "klefki", types: ["はがね", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 142, name: "ハガネール", slug: "steelix", types: ["はがね", "じめん"], immune_types: [], resist_types: [] },
  { rank: 142.1, name: "メガハガネール", slug: "steelix-mega", types: ["はがね", "じめん"], immune_types: [], resist_types: [] },
  { rank: 143, name: "ドダイトス", slug: "torterra", types: ["くさ", "じめん"], immune_types: [], resist_types: [] },
  { rank: 144, name: "ワルビアル", slug: "krookodile", types: ["じめん", "あく"], immune_types: [], resist_types: [] },
  { rank: 145, name: "サンダース", slug: "jolteon", types: ["でんき"], immune_types: ["でんき"], resist_types: [] },
  { rank: 146, name: "ケケンカニ", slug: "crabominable", types: ["かくとう", "こおり"], immune_types: [], resist_types: [] },
  { rank: 146.1, name: "メガケケンカニ", slug: "crabominable-mega", types: ["かくとう", "こおり"], immune_types: [], resist_types: [] },
  { rank: 147, name: "キョジオーン", slug: "garganacl", types: ["いわ"], immune_types: [], resist_types: ["ゴースト"] },
  { rank: 148, name: "ミカルゲ", slug: "spiritomb", types: ["ゴースト", "あく"], immune_types: [], resist_types: [] },
  { rank: 149, name: "ヌメルゴン", slug: "goodra", types: ["ドラゴン"], immune_types: ["くさ"], resist_types: [] },
  { rank: 150, name: "カイリキー", slug: "machamp", types: ["かくとう"], immune_types: [], resist_types: [] },
  { rank: 151, name: "オンバーン", slug: "noivern", types: ["ひこう", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 152, name: "ジャラランガ", slug: "kommo-o", types: ["ドラゴン", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 153, name: "アリアドス", slug: "ariados", types: ["むし", "どく"], immune_types: [], resist_types: [] },
  { rank: 154, name: "デンリュウ", slug: "ampharos", types: ["でんき"], immune_types: [], resist_types: [] },
  { rank: 154.1, name: "メガデンリュウ", slug: "ampharos-mega", types: ["でんき", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 155, name: "ムシャーナ", slug: "musharna", types: ["エスパー"], immune_types: [], resist_types: [] },
  { rank: 156, name: "ブロスター", slug: "clawitzer", types: ["みず"], immune_types: [], resist_types: [] },
  { rank: 157, name: "アマージョ", slug: "tsareena", types: ["くさ"], immune_types: [], resist_types: [] },
  { rank: 158, name: "ペロリーム", slug: "slurpuff", types: ["フェアリー"], immune_types: [], resist_types: [] },
  { rank: 159, name: "オニゴーリ", slug: "glalie", types: ["こおり"], immune_types: [], resist_types: [] },
  { rank: 159.1, name: "メガオニゴーリ", slug: "glalie-mega", types: ["こおり"], immune_types: [], resist_types: [] },
  { rank: 160, name: "ピジョット", slug: "pidgeot", types: ["ノーマル", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 160.1, name: "メガピジョット", slug: "pidgeot-mega", types: ["ノーマル", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 161, name: "ヤドキング", slug: "slowking", types: ["みず", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 162, name: "ジジーロン", slug: "drampa", types: ["ノーマル", "ドラゴン"], immune_types: ["くさ"], resist_types: [] },
  { rank: 162.1, name: "メガジジーロン", slug: "drampa-mega", types: ["ノーマル", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 163, name: "ゾロアーク", slug: "zoroark", types: ["あく"], immune_types: [], resist_types: [] },
  { rank: 164, name: "フォレトス", slug: "forretress", types: ["むし", "はがね"], immune_types: [], resist_types: [] },
  { rank: 165, name: "カミツオロチ", slug: "hydrapple", types: ["くさ", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 166, name: "モルペコ", slug: "morpeko", types: ["でんき", "あく"], immune_types: [], resist_types: [] },
  { rank: 167, name: "ゴルーグ", slug: "golurk", types: ["じめん", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 167.1, name: "メガゴルーグ", slug: "golurk-mega", types: ["じめん", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 168, name: "キュウコン", slug: "ninetales", types: ["ほのお"], immune_types: ["ほのお"], resist_types: [] },
  { rank: 169, name: "チャーレム", slug: "medicham", types: ["かくとう", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 169.1, name: "メガチャーレム", slug: "medicham-mega", types: ["かくとう", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 170, name: "アマルルガ", slug: "aurorus", types: ["いわ", "こおり"], immune_types: [], resist_types: [] },
  { rank: 171, name: "タイレーツ", slug: "falinks", types: ["かくとう"], immune_types: [], resist_types: [] },
  { rank: 171.1, name: "メガタイレーツ", slug: "falinks-mega", types: ["かくとう"], immune_types: [], resist_types: [] },
  { rank: 172, name: "リキキリン", slug: "farigiraf", types: ["ノーマル", "エスパー"], immune_types: ["くさ"], resist_types: [] },
  { rank: 173, name: "オーロット", slug: "trevenant", types: ["ゴースト", "くさ"], immune_types: [], resist_types: [] },
  { rank: 174, name: "ドサイドン", slug: "rhyperior", types: ["じめん", "いわ"], immune_types: ["でんき"], resist_types: [] },
  { rank: 175, name: "ニャオニクス(オス)", slug: "meowstic", types: ["エスパー"], immune_types: [], resist_types: [] },
  { rank: 175.1, name: "メガニャオニクス(オス)", slug: "meowstic", types: ["エスパー"], immune_types: [], resist_types: [] },
  { rank: 176, name: "ヘルガー", slug: "houndoom", types: ["あく", "ほのお"], immune_types: ["ほのお"], resist_types: [] },
  { rank: 176.1, name: "メガヘルガー", slug: "houndoom-mega", types: ["あく", "ほのお"], immune_types: [], resist_types: [] },
  { rank: 177, name: "アブソル", slug: "absol", types: ["あく"], immune_types: [], resist_types: [] },
  { rank: 177.1, name: "メガアブソル", slug: "absol-mega", types: ["あく"], immune_types: [], resist_types: [] },
  { rank: 178, name: "エンブオー", slug: "emboar", types: ["ほのお", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 178.1, name: "メガエンブオー", slug: "emboar-mega", types: ["ほのお", "かくとう"], immune_types: [], resist_types: [] },
  { rank: 179, name: "クレベース", slug: "avalugg", types: ["こおり"], immune_types: [], resist_types: [] },
  { rank: 180, name: "ピカチュウ", slug: "pikachu", types: ["でんき"], immune_types: ["でんき"], resist_types: [] },
  { rank: 181, name: "バリコオル", slug: "mr-rime", types: ["こおり", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 182, name: "マッギョ", slug: "stunfisk", types: ["じめん", "でんき"], immune_types: [], resist_types: [] },
  { rank: 183, name: "マホイップ", slug: "alcremie", types: ["フェアリー"], immune_types: [], resist_types: [] },
  { rank: 184, name: "リーフィア", slug: "leafeon", types: ["くさ"], immune_types: [], resist_types: [] },
  { rank: 185, name: "ケンタロス(水)", slug: "tauros-paldea-aqua", types: ["かくとう", "みず"], immune_types: [], resist_types: [] },
  { rank: 186, name: "ロズレイド", slug: "roserade", types: ["くさ", "どく"], immune_types: [], resist_types: [] },
  { rank: 187, name: "サダイジャ", slug: "sandaconda", types: ["じめん"], immune_types: [], resist_types: [] },
  { rank: 188, name: "ライボルト", slug: "manectric", types: ["でんき"], immune_types: ["でんき"], resist_types: [] },
  { rank: 188.1, name: "メガライボルト", slug: "manectric-mega", types: ["でんき"], immune_types: [], resist_types: [] },
  { rank: 189, name: "エモンガ", slug: "emolga", types: ["でんき", "ひこう"], immune_types: [], resist_types: [] },
  { rank: 190, name: "ガチゴラス", slug: "tyrantrum", types: ["いわ", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 191, name: "フロストロトム", slug: "rotom-frost", types: ["でんき", "こおり"], immune_types: ["じめん"], resist_types: [] },
  { rank: 192, name: "バクーダ", slug: "camerupt", types: ["ほのお", "じめん"], immune_types: [], resist_types: [] },
  { rank: 192.1, name: "メガバクーダ", slug: "camerupt-mega", types: ["ほのお", "じめん"], immune_types: [], resist_types: [] },
  { rank: 193, name: "バクフーン", slug: "typhlosion", types: ["ほのお"], immune_types: ["ほのお"], resist_types: [] },
  { rank: 194, name: "トリデプス", slug: "bastiodon", types: ["いわ", "はがね"], immune_types: [], resist_types: [] },
  { rank: 195, name: "クレベース(ヒスイ)", slug: "avalugg-hisui", types: ["こおり", "いわ"], immune_types: [], resist_types: [] },
  { rank: 196, name: "ブースター", slug: "flareon", types: ["ほのお"], immune_types: ["ほのお"], resist_types: [] },
  { rank: 197, name: "アーボック", slug: "arbok", types: ["どく"], immune_types: [], resist_types: [] },
  { rank: 198, name: "ドクロッグ", slug: "toxicroak", types: ["どく", "かくとう"], immune_types: ["みず"], resist_types: [] },
  { rank: 199, name: "ゴロンダ", slug: "pangoro", types: ["かくとう", "あく"], immune_types: [], resist_types: [] },
  { rank: 200, name: "フラージェス", slug: "florges", types: ["フェアリー"], immune_types: [], resist_types: [] },
  { rank: 201, name: "パンプジン(とくだい)", slug: "gourgeist-super", types: ["ゴースト", "くさ"], immune_types: [], resist_types: [] },
  { rank: 202, name: "レパルダス", slug: "liepard", types: ["あく"], immune_types: [], resist_types: [] },
  { rank: 203, name: "ツンベアー", slug: "beartic", types: ["こおり"], immune_types: [], resist_types: [] },
  { rank: 204, name: "レントラー", slug: "luxray", types: ["でんき"], immune_types: [], resist_types: [] },
  { rank: 205, name: "ラムパルド", slug: "rampardos", types: ["いわ"], immune_types: [], resist_types: [] },
  { rank: 206, name: "ニャオニクス(メス)", slug: "meowstic-f", types: ["エスパー"], immune_types: [], resist_types: [] },
  { rank: 206.1, name: "メガニャオニクス(メス)", slug: "meowstic-f", types: ["エスパー"], immune_types: [], resist_types: [] },
  { rank: 207, name: "ジュナイパー", slug: "decidueye", types: ["くさ", "ゴースト"], immune_types: [], resist_types: [] },
  { rank: 208, name: "タブンネ", slug: "audino", types: ["ノーマル"], immune_types: [], resist_types: [] },
  { rank: 208.1, name: "メガタブンネ", slug: "audino-mega", types: ["ノーマル", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 209, name: "デデンネ", slug: "dedenne", types: ["でんき", "フェアリー"], immune_types: [], resist_types: [] },
  { rank: 210, name: "アヤシシ", slug: "wyrdeer", types: ["ノーマル", "エスパー"], immune_types: ["くさ"], resist_types: [] },
  { rank: 211, name: "タルップル", slug: "appletun", types: ["くさ", "ドラゴン"], immune_types: [], resist_types: ["ほのお", "こおり"] },
  { rank: 212, name: "ハリーセン", slug: "tentacruel", types: ["みず", "どく"], immune_types: [], resist_types: [] },
  { rank: 213, name: "トリミアン", slug: "furfrou", types: ["ノーマル"], immune_types: [], resist_types: [] },
  { rank: 214, name: "スピンロトム", slug: "rotom-fan", types: ["でんき", "ひこう"], immune_types: ["じめん"], resist_types: [] },
  { rank: 215, name: "マッギョ(ガラル)", slug: "stunfisk-galar", types: ["じめん", "はがね"], immune_types: [], resist_types: [] },
  { rank: 216, name: "ケンタロス", slug: "tauros", types: ["ノーマル"], immune_types: [], resist_types: [] },
  { rank: 217, name: "ライチュウ(アローラ)", slug: "raichu-alola", types: ["でんき", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 218, name: "ロトム", slug: "rotom", types: ["でんき", "ゴースト"], immune_types: ["じめん"], resist_types: [] },
  { rank: 219, name: "ダイケンキ", slug: "samurott", types: ["みず"], immune_types: [], resist_types: [] },
  { rank: 220, name: "ルガルガン(まよなか)", slug: "lycanroc-midnight", types: ["いわ"], immune_types: [], resist_types: [] },
  { rank: 221, name: "ルガルガン(まひる)", slug: "lycanroc", types: ["いわ"], immune_types: [], resist_types: [] },
  { rank: 222, name: "ダストダス", slug: "garbodor", types: ["どく"], immune_types: [], resist_types: [] },
  { rank: 223, name: "アップリュー", slug: "flapple", types: ["くさ", "ドラゴン"], immune_types: [], resist_types: [] },
  { rank: 224, name: "ヤレユータン", slug: "oranguru", types: ["ノーマル", "エスパー"], immune_types: [], resist_types: [] },
  { rank: 225, name: "フレフワン", slug: "aromatisse", types: ["フェアリー"], immune_types: [], resist_types: [] },
  { rank: 226, name: "パンプジン(おおきい)", slug: "gourgeist-large", types: ["ゴースト", "くさ"], immune_types: [], resist_types: [] },
  { rank: 227, name: "パンプジン(ふつう)", slug: "gourgeist", types: ["ゴースト", "くさ"], immune_types: [], resist_types: [] },
  { rank: 228, name: "ナゲツケサル", slug: "passimian", types: ["かくとう"], immune_types: [], resist_types: [] },
  { rank: 229, name: "ヒヤッキー", slug: "simipour", types: ["みず"], immune_types: [], resist_types: [] },
  { rank: 230, name: "バオッキー", slug: "simisear", types: ["ほのお"], immune_types: [], resist_types: [] },
  { rank: 231, name: "パンプジン(ちいさい)", slug: "gourgeist-small", types: ["ゴースト", "くさ"], immune_types: [], resist_types: [] },
  { rank: 232, name: "ケンタロス(格)", slug: "tauros-paldea-combat", types: ["かくとう"], immune_types: [], resist_types: [] },
  { rank: 233, name: "ポワルン", slug: "castform", types: ["ノーマル"], immune_types: [], resist_types: [] },
  { rank: 234, name: "ミルホッグ", slug: "watchog", types: ["ノーマル"], immune_types: [], resist_types: [] },
  { rank: 235, name: "ヤナッキー", slug: "simisage", types: ["くさ"], immune_types: [], resist_types: [] },
];

// =========================================================
// ITEM_LIST
// スプライト素材: msikma/pokesprite (items-outline)
// category: "hold-item" | "berry" | "mega-stone" | "plate" | "z-crystal"
// URL変換ルール（index.html の ITEM_SPRITE_URL 参照）
// =========================================================
const ITEM_LIST = [
  // ===== 持ち物 =====
  { name: "きゅうこん",         slug: "absorb-bulb",      category: "hold-item" },
  { name: "こんごうだま",       slug: "adamant-orb",      category: "hold-item" },
  { name: "びびりだま",         slug: "adrenaline-orb",   category: "hold-item" },
  { name: "ふうせん",           slug: "air-balloon",      category: "hold-item" },
  { name: "とつげきチョッキ",   slug: "assault-vest",     category: "hold-item" },
  { name: "おおきなねっこ",     slug: "big-root",         category: "hold-item" },
  { name: "しめつけバンド",     slug: "binding-band",     category: "hold-item" },
  { name: "くろおび",           slug: "black-belt",       category: "hold-item" },
  { name: "くろいメガネ",       slug: "black-glasses",    category: "hold-item" },
  { name: "くろいヘドロ",       slug: "black-sludge",     category: "hold-item" },
  { name: "あいいろのたま",     slug: "blue-orb",         category: "hold-item" },
  { name: "からぶりほけん",     slug: "blunder-policy",   category: "hold-item" },
  { name: "ひかりのこな",       slug: "bright-powder",    category: "hold-item" },
  { name: "ブレイズカセット",   slug: "burn-drive",       category: "hold-item" },
  { name: "じゅうでんち",       slug: "cell-battery",     category: "hold-item" },
  { name: "もくたん",           slug: "charcoal",         category: "hold-item" },
  { name: "フリーズカセット",   slug: "chill-drive",      category: "hold-item" },
  { name: "こだわりハチマキ",   slug: "choice-band",      category: "hold-item" },
  { name: "こだわりスカーフ",   slug: "choice-scarf",     category: "hold-item" },
  { name: "こだわりメガネ",     slug: "choice-specs",     category: "hold-item" },
  { name: "きよめのおふだ",     slug: "cleanse-tag",      category: "hold-item" },
  { name: "しめったいわ",       slug: "damp-rock",        category: "hold-item" },
  { name: "あかいいと",         slug: "destiny-knot",     category: "hold-item" },
  { name: "アクアカセット",     slug: "douse-drive",      category: "hold-item" },
  { name: "りゅうのキバ",       slug: "dragon-fang",      category: "hold-item" },
  { name: "だっしゅつボタン",   slug: "eject-button",     category: "hold-item" },
  { name: "だっしゅつパック",   slug: "eject-pack",       category: "hold-item" },
  { name: "エレキシード",       slug: "electric-seed",    category: "hold-item" },
  { name: "かわらずのいし",     slug: "everstone",        category: "hold-item" },
  { name: "しんかのきせき",     slug: "eviolite",         category: "hold-item" },
  { name: "たつじんのおび",     slug: "expert-belt",      category: "hold-item" },
  { name: "かえんだま",         slug: "flame-orb",        category: "hold-item" },
  { name: "かるいし",           slug: "float-stone",      category: "hold-item" },
  { name: "きあいのハチマキ",   slug: "focus-band",       category: "hold-item" },
  { name: "きあいのタスキ",     slug: "focus-sash",       category: "hold-item" },
  { name: "グラスシード",       slug: "grassy-seed",      category: "hold-item" },
  { name: "ねばりのかぎづめ",   slug: "grip-claw",        category: "hold-item" },
  { name: "はっきんだま",       slug: "griseous-orb",     category: "hold-item" },
  { name: "かたいいし",         slug: "hard-stone",       category: "hold-item" },
  { name: "あついいわ",         slug: "heat-rock",        category: "hold-item" },
  { name: "あつぞこブーツ",     slug: "heavy-duty-boots", category: "hold-item" },
  { name: "つめたいいわ",       slug: "icy-rock",         category: "hold-item" },
  { name: "くろいてっきゅう",   slug: "iron-ball",        category: "hold-item" },
  { name: "おうじゃのしるし",   slug: "kings-rock",       category: "hold-item" },
  { name: "こうこうのしっぽ",     slug: "lagging-tail",     category: "hold-item" },
  { name: "たべのこし",         slug: "leftovers",        category: "hold-item" },
  { name: "いのちのたま",       slug: "life-orb",         category: "hold-item" },
  { name: "でんきだま",         slug: "light-ball",       category: "hold-item" },
  { name: "ひかりのねんど",     slug: "light-clay",       category: "hold-item" },
  { name: "ラッキーパンチ",     slug: "lucky-punch",      category: "hold-item" },
  { name: "ひかりごけ",         slug: "luminous-moss",    category: "hold-item" },
  { name: "しらたま",           slug: "lustrous-orb",     category: "hold-item" },
  { name: "じしゃく",           slug: "magnet",           category: "hold-item" },
  { name: "メンタルハーブ",     slug: "mental-herb",      category: "hold-item" },
  { name: "メタルコート",       slug: "metal-coat",       category: "hold-item" },
  { name: "メタルパウダー",     slug: "metal-powder",     category: "hold-item" },
  { name: "メトロノーム",       slug: "metronome",        category: "hold-item" },
  { name: "きせきのタネ",       slug: "miracle-seed",     category: "hold-item" },
  { name: "ミストシード",       slug: "misty-seed",       category: "hold-item" },
  { name: "ちからのハチマキ",   slug: "muscle-band",      category: "hold-item" },
  { name: "しんぴのしずく",     slug: "mystic-water",     category: "hold-item" },
  { name: "とけないこおり",     slug: "never-melt-ice",   category: "hold-item" },
  { name: "どくバリ",           slug: "poison-barb",      category: "hold-item" },
  { name: "パワフルハーブ",     slug: "power-herb",       category: "hold-item" },
  { name: "ぼうごパッド",       slug: "protective-pads",  category: "hold-item" },
  { name: "サイコシード",       slug: "psychic-seed",     category: "hold-item" },
  { name: "せんせいのツメ",     slug: "quick-claw",       category: "hold-item" },
  { name: "スピードパウダー",   slug: "quick-powder",     category: "hold-item" },
  { name: "レッドカード",       slug: "red-card",         category: "hold-item" },
  { name: "べにいろのたま",     slug: "red-orb",          category: "hold-item" },
  { name: "ねらいのまと",       slug: "ring-target",      category: "hold-item" },
  { name: "ゴツゴツメット",     slug: "rocky-helmet",     category: "hold-item" },
  { name: "ルームサービス",     slug: "room-service",     category: "hold-item" },
  { name: "さびたたて",         slug: "rusted-shield",    category: "hold-item" },
  { name: "さびたつるぎ",       slug: "rusted-sword",     category: "hold-item" },
  { name: "ぼうじんゴーグル",   slug: "safety-goggles",   category: "hold-item" },
  { name: "ピントレンズ",       slug: "scope-lens",       category: "hold-item" },
  { name: "するどいくちばし",   slug: "sharp-beak",       category: "hold-item" },
  { name: "きれいなぬけがら",   slug: "shed-shell",       category: "hold-item" },
  { name: "かいがらのすず",     slug: "shell-bell",       category: "hold-item" },
  { name: "イナズマカセット",   slug: "shock-drive",      category: "hold-item" },
  { name: "シルクのスカーフ",   slug: "silk-scarf",       category: "hold-item" },
  { name: "ぎんのこな",         slug: "silver-powder",    category: "hold-item" },
  { name: "さらさらいわ",       slug: "smooth-rock",      category: "hold-item" },
  { name: "ゆきだま",           slug: "snowball",         category: "hold-item" },
  { name: "やわらかいすな",     slug: "soft-sand",        category: "hold-item" },
  { name: "こころのしずく",     slug: "soul-dew",         category: "hold-item" },
  { name: "のろいのおふだ",     slug: "spell-tag",        category: "hold-item" },
  { name: "ながねぎ",           slug: "stick",            category: "hold-item" },
  { name: "くっつきバリ",       slug: "sticky-barb",      category: "hold-item" },
  { name: "ちびきかくだい",     slug: "terrain-extender", category: "hold-item" },
  { name: "ふといほね",         slug: "thick-club",       category: "hold-item" },
  { name: "のどスプレー",       slug: "throat-spray",     category: "hold-item" },
  { name: "どくどくだま",       slug: "toxic-orb",        category: "hold-item" },
  { name: "まがったスプーン",   slug: "twisted-spoon",    category: "hold-item" },
  { name: "ばんのうがさ",       slug: "utility-umbrella", category: "hold-item" },
  { name: "じゃくてんほけん",   slug: "weakness-policy",  category: "hold-item" },
  { name: "しろいハーブ",       slug: "white-herb",       category: "hold-item" },
  { name: "こうかくレンズ",     slug: "wide-lens",        category: "hold-item" },
  { name: "ものしりメガネ",     slug: "wise-glasses",     category: "hold-item" },
  { name: "フォーカスレンズ",   slug: "zoom-lens",        category: "hold-item" },
  // ===== きのみ =====
  { name: "バンジのみ",   slug: "aguav-berry",   category: "berry" },
  { name: "ズアのみ",     slug: "apicot-berry",  category: "berry" },
  { name: "ナナシのみ",   slug: "aspear-berry",  category: "berry" },
  { name: "リリバのみ",   slug: "babiri-berry",  category: "berry" },
  { name: "ベリブのみ",     slug: "belue-berry",   category: "berry" },
  { name: "ブリーのみ",   slug: "bluk-berry",    category: "berry" },
  { name: "ヨロギのみ",   slug: "charti-berry",  category: "berry" },
  { name: "クラボのみ",   slug: "cheri-berry",   category: "berry" },
  { name: "カゴのみ",     slug: "chesto-berry",  category: "berry" },
  { name: "ホズのみ",   slug: "chilan-berry",  category: "berry" },
  { name: "ヨプのみ",   slug: "chople-berry",  category: "berry" },
  { name: "バコウのみ",   slug: "coba-berry",    category: "berry" },
  { name: "ナモのみ",   slug: "colbur-berry",  category: "berry" },
  { name: "モコシのみ",   slug: "cornn-berry",   category: "berry" },
  { name: "イバンのみ",     slug: "custap-berry",  category: "berry" },
  { name: "ドリのみ",     slug: "durin-berry",   category: "berry" },
  { name: "ナゾのみ",     slug: "enigma-berry",  category: "berry" },
  { name: "フィラのみ",   slug: "figy-berry",    category: "berry" },
  { name: "リュガのみ",   slug: "ganlon-berry",  category: "berry" },
  { name: "ウブのみ",     slug: "grepa-berry",   category: "berry" },
  { name: "ハバンのみ",   slug: "haban-berry",   category: "berry" },
  { name: "ロメのみ",   slug: "hondew-berry",  category: "berry" },
  { name: "イアのみ",     slug: "iapapa-berry",  category: "berry" },
  { name: "ジャポのみ",   slug: "jaboca-berry",  category: "berry" },
  { name: "カシブのみ",     slug: "kasib-berry",   category: "berry" },
  { name: "ビアーのみ",     slug: "kebia-berry",   category: "berry" },
  { name: "アッキのみ",     slug: "kee-berry",     category: "berry" },
  { name: "ネコブのみ",   slug: "kelpsy-berry",  category: "berry" },
  { name: "サンのみ", slug: "lansat-berry",  category: "berry" },
  { name: "ヒメリのみ",   slug: "leppa-berry",   category: "berry" },
  { name: "チイラのみ",   slug: "liechi-berry",  category: "berry" },
  { name: "ラムのみ",     slug: "lum-berry",     category: "berry" },
  { name: "マゴのみ",     slug: "mago-berry",    category: "berry" },
  { name: "ゴスのみ",     slug: "magost-berry",  category: "berry" },
  { name: "タラプのみ",   slug: "maranga-berry", category: "berry" },
  { name: "ミクルのみ",   slug: "micle-berry",   category: "berry" },
  { name: "ナナのみ",   slug: "nanab-berry",   category: "berry" },
  { name: "ノメルのみ",     slug: "nomel-berry",   category: "berry" },
  { name: "オッカのみ",   slug: "occa-berry",    category: "berry" },
  { name: "オレンのみ",   slug: "oran-berry",    category: "berry" },
  { name: "シーヤのみ",     slug: "pamtre-berry",  category: "berry" },
  { name: "イトケのみ",   slug: "passho-berry",  category: "berry" },
  { name: "ウタンのみ",     slug: "payapa-berry",  category: "berry" },
  { name: "モモンのみ",   slug: "pecha-berry",   category: "berry" },
  { name: "キーのみ",   slug: "persim-berry",  category: "berry" },
  { name: "ヤタピのみ",     slug: "petaya-berry",  category: "berry" },
  { name: "パイルのみ",   slug: "pinap-berry",   category: "berry" },
  { name: "ザロクのみ",   slug: "pomeg-berry",   category: "berry" },
  { name: "タポルのみ",   slug: "qualot-berry",  category: "berry" },
  { name: "ラブタのみ",   slug: "rabuta-berry",  category: "berry" },
  { name: "チーゴのみ",   slug: "rawst-berry",   category: "berry" },
  { name: "ズリのみ",     slug: "razz-berry",    category: "berry" },
  { name: "リンドのみ",   slug: "rindo-berry",   category: "berry" },
  { name: "ロゼルのみ",   slug: "roseli-berry",  category: "berry" },
  { name: "レンブのみ",   slug: "rowap-berry",   category: "berry" },
  { name: "カムラのみ",   slug: "salac-berry",   category: "berry" },
  { name: "シュカのみ",   slug: "shuca-berry",   category: "berry" },
  { name: "オボンのみ",     slug: "sitrus-berry",  category: "berry" },
  { name: "ノワキのみ",   slug: "spelon-berry",  category: "berry" },
  { name: "スターのみ",     slug: "starf-berry",   category: "berry" },
  { name: "マトマのみ",     slug: "tamato-berry",  category: "berry" },
  { name: "タンガのみ",   slug: "tanga-berry",   category: "berry" },
  { name: "ソクノのみ",   slug: "wacan-berry",   category: "berry" },
  { name: "カイスのみ",   slug: "watmel-berry",  category: "berry" },
  { name: "セシナのみ",   slug: "wepear-berry",  category: "berry" },
  { name: "ウイのみ",     slug: "wiki-berry",    category: "berry" },
  { name: "ヤチェのみ",   slug: "yache-berry",   category: "berry" },
  // ===== メガストーン =====
  { name: "ユキノオーナイト",   slug: "abomasite",      category: "mega-stone" },
  { name: "アブソルナイト",     slug: "absolite",       category: "mega-stone" },
  { name: "プテラナイト",       slug: "aerodactylite",  category: "mega-stone" },
  { name: "ボスゴドラナイト",   slug: "aggronite",      category: "mega-stone" },
  { name: "フーディナイト",     slug: "alakazite",      category: "mega-stone" },
  { name: "チルタリスナイト",   slug: "altarianite",    category: "mega-stone" },
  { name: "デンリュウナイト",   slug: "ampharosite",    category: "mega-stone" },
  { name: "タブンネナイト",     slug: "audinite",       category: "mega-stone" },
  { name: "ジュペッタナイト",   slug: "banettite",      category: "mega-stone" },
  { name: "スピアーナイト",     slug: "beedrillite",    category: "mega-stone" },
  { name: "カメックスナイト",   slug: "blastoisinite",  category: "mega-stone" },
  { name: "バシャーモナイト",   slug: "blazikenite",    category: "mega-stone" },
  { name: "カメールナイト",     slug: "cameruptite",    category: "mega-stone" },
  { name: "リザードナイトX",   slug: "charizardite-x", category: "mega-stone" },
  { name: "リザードナイトY",   slug: "charizardite-y", category: "mega-stone" },
  { name: "ディアンシナイト",   slug: "diancite",       category: "mega-stone" },
  { name: "エルレイドナイト",   slug: "galladite",      category: "mega-stone" },
  { name: "ガブリアスナイト",   slug: "garchompite",    category: "mega-stone" },
  { name: "サーナイトナイト",   slug: "gardevoirite",   category: "mega-stone" },
  { name: "ゲンガナイト",       slug: "gengarite",      category: "mega-stone" },
  { name: "オニゴーリナイト",   slug: "glalitite",      category: "mega-stone" },
  { name: "ギャラドスナイト",   slug: "gyaradosite",    category: "mega-stone" },
  { name: "ヘラクロスナイト",   slug: "heracronite",    category: "mega-stone" },
  { name: "ヘルガーナイト",     slug: "houndoominite",  category: "mega-stone" },
  { name: "ガルーラナイト",     slug: "kangaskhanite",  category: "mega-stone" },
  { name: "ラティアスナイト",   slug: "latiasite",      category: "mega-stone" },
  { name: "ラティオスナイト",   slug: "latiosite",      category: "mega-stone" },
  { name: "ミミロップナイト",   slug: "lopunnite",      category: "mega-stone" },
  { name: "ルカリオナイト",     slug: "lucarionite",    category: "mega-stone" },
  { name: "ライボルトナイト",   slug: "manectite",      category: "mega-stone" },
  { name: "マリルリナイト",     slug: "mawilite",       category: "mega-stone" },
  { name: "チャーレムナイト",   slug: "medichamite",    category: "mega-stone" },
  { name: "メタグロスナイト",   slug: "metagrossite",   category: "mega-stone" },
  { name: "ミュウツーナイトX", slug: "mewtwonite-x",   category: "mega-stone" },
  { name: "ミュウツーナイトY", slug: "mewtwonite-y",   category: "mega-stone" },
  { name: "ピジョットナイト",   slug: "pidgeotite",     category: "mega-stone" },
  { name: "カイロスナイト",     slug: "pinsirite",      category: "mega-stone" },
  { name: "ヤミカラスナイト",   slug: "sablenite",      category: "mega-stone" },
  { name: "ボーマンダナイト",   slug: "salamencite",    category: "mega-stone" },
  { name: "ジュカインナイト",   slug: "sceptilite",     category: "mega-stone" },
  { name: "ハッサムナイト",     slug: "scizorite",      category: "mega-stone" },
  { name: "サメハダーナイト",   slug: "sharpedonite",   category: "mega-stone" },
  { name: "ヤドランナイト",     slug: "slowbronite",    category: "mega-stone" },
  { name: "ハガネールナイト",   slug: "steelixite",     category: "mega-stone" },
  { name: "ラグラージナイト",   slug: "swampertite",    category: "mega-stone" },
  { name: "バンギラスナイト",   slug: "tyranitarite",   category: "mega-stone" },
  { name: "フシギバナイト",     slug: "venusaurite",    category: "mega-stone" },
  // ===== プレート =====
  { name: "りゅうのプレート",   slug: "draco-plate",  category: "plate" },
  { name: "こわもてプレート",   slug: "dread-plate",  category: "plate" },
  { name: "だいちのプレート",   slug: "earth-plate",  category: "plate" },
  { name: "こぶしのプレート",   slug: "fist-plate",   category: "plate" },
  { name: "ひのたまプレート",   slug: "flame-plate",  category: "plate" },
  { name: "つららのプレート",   slug: "icicle-plate", category: "plate" },
  { name: "たまむしプレート",   slug: "insect-plate", category: "plate" },
  { name: "こうてつプレート",   slug: "iron-plate",   category: "plate" },
  { name: "みどりのプレート",   slug: "meadow-plate", category: "plate" },
  { name: "ふしぎのプレート",   slug: "mind-plate",   category: "plate" },
  { name: "せいれいプレート",   slug: "pixie-plate",  category: "plate" },
  { name: "そらのプレート",     slug: "sky-plate",    category: "plate" },
  { name: "しずくプレート",     slug: "splash-plate", category: "plate" },
  { name: "もののけプレート",   slug: "spooky-plate", category: "plate" },
  { name: "がんせきプレート",   slug: "stone-plate",  category: "plate" },
  { name: "もうどくプレート",   slug: "toxic-plate",  category: "plate" },
  { name: "いなずまプレート",   slug: "zap-plate",    category: "plate" },
  // ===== Zクリスタル =====
  { name: "ライチュウZ",           slug: "aloraichium-z",   category: "z-crystal" },
  { name: "むしZ",                 slug: "buginium-z",      category: "z-crystal" },
  { name: "あくZ",                 slug: "darkinium-z",     category: "z-crystal" },
  { name: "ジュナイパーZ",         slug: "decidium-z",      category: "z-crystal" },
  { name: "ドラゴンZ",             slug: "dragonium-z",     category: "z-crystal" },
  { name: "イーブイZ",             slug: "eevium-z",        category: "z-crystal" },
  { name: "でんきZ",               slug: "electrium-z",     category: "z-crystal" },
  { name: "フェアリーZ",           slug: "fairium-z",       category: "z-crystal" },
  { name: "かくとうZ",             slug: "fightinium-z",    category: "z-crystal" },
  { name: "ほのおZ",               slug: "firium-z",        category: "z-crystal" },
  { name: "ひこうZ",               slug: "flyinium-z",      category: "z-crystal" },
  { name: "ゴーストZ",             slug: "ghostium-z",      category: "z-crystal" },
  { name: "くさZ",                 slug: "grassium-z",      category: "z-crystal" },
  { name: "じめんZ",               slug: "groundium-z",     category: "z-crystal" },
  { name: "こおりZ",               slug: "icium-z",         category: "z-crystal" },
  { name: "ガオガエンZ",           slug: "incinium-z",      category: "z-crystal" },
  { name: "ジャラランガZ",         slug: "kommonium-z",     category: "z-crystal" },
  { name: "ルナアーラZ",           slug: "lunalium-z",      category: "z-crystal" },
  { name: "ルガルガンZ",           slug: "lycanium-z",      category: "z-crystal" },
  { name: "マーシャドーZ",         slug: "marshadium-z",    category: "z-crystal" },
  { name: "ミュウZ",               slug: "mewnium-z",       category: "z-crystal" },
  { name: "ミミッキュZ",           slug: "mimikium-z",      category: "z-crystal" },
  { name: "ノーマルZ",             slug: "normalium-z",     category: "z-crystal" },
  { name: "ピカチュウZ",           slug: "pikanium-z",      category: "z-crystal" },
  { name: "ピカチュウZ（Ash）",    slug: "pikashunium-z",   category: "z-crystal" },
  { name: "どくZ",                 slug: "poisonium-z",     category: "z-crystal" },
  { name: "アシレーヌZ",           slug: "primarium-z",     category: "z-crystal" },
  { name: "エスパーZ",             slug: "psychium-z",      category: "z-crystal" },
  { name: "いわZ",                 slug: "rockium-z",       category: "z-crystal" },
  { name: "カビゴンZ",             slug: "snorlium-z",      category: "z-crystal" },
  { name: "ソルガレオZ",           slug: "solganium-z",     category: "z-crystal" },
  { name: "はがねZ",               slug: "steelium-z",      category: "z-crystal" },
  { name: "カプZ",                 slug: "tapunium-z",      category: "z-crystal" },
  { name: "ウルトラネクロズマZ",   slug: "ultranecrozium-z", category: "z-crystal" },
  { name: "みずZ",                 slug: "waterium-z",      category: "z-crystal" },
];